stages:
 - pretest
 
pretest:
  image: python:3.7.9-stretch
  stage: pretest
  script:
    # Setting the Execution Script to Ensure Bot Can At Bare Minimum Login
    - python -m pip install --upgrade pip
    - pip install flake8 pytest
    - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi; python3 coderbot.py function.py bot.py redditAPI.py"
    
  artifacts:
    paths:
      - ./IMAGE.env
  except:
    - master
  
