
steps:
  - name: checkout
    uses: actions/checkout@v2
  - name: Auto Issue List in README
    on:
      schedule:
        - cron: "* */1 * * *"
    uses: seed-of-apricot/issue-list-readme@v1.1.0
    with:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      pattern: '<!-- openIssueTable -->
      labels: 'open'
  - name: Completed Issue List
    on:
      schedule:
        - cron: "* */1 * * *"
    uses: seed-of-apricot/issue-list-readme@v1.1.0
    with:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      pattern: '<!-- closedIssueTable -->
      labels: 'closed'
  
